
# 1
- name: Start and enable Docker service
  ansible.builtin.service:
    name: "{{ docker_service_name[ansible_distribution] }}"
    state: started
    enabled: yes

#2
- name: Ensure(create) Docker group exists
  ansible.builtin.group:
    name: docker
    state: present

#3
- name: Add current user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Get ECR login token
  shell: |
    aws ecr get-login-password --region {{ aws_region }} 
  register: ecr_token

- name: Debug ECR Token
  debug: 
    var: ecr_token

- name: Login into ECR registry
  community.docker.docker_login:
    registry_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
    username: AWS
    password: "{{ ecr_token.stdout }}"
    reauthorize: yes
  register: docker_login_result

- name: Debug ECR Token
  debug: 
    var: docker_login_result

- name: Pull latest Backend image
  docker_image:
    name: "{{ backend_ecr_uri }}:latest"
    source: pull
    force_source: yes




