- name: Install unzip and curl (required for AWS CLI install)
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes
  become: yes

- name: Download AWS CLI v2 installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
  become: yes

- name: Unzip AWS CLI installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes
  become: yes

- name: Install AWS CLI
  command: "/tmp/aws/install"
  args:
    creates: /usr/local/bin/aws
  become: yes

- name: Verify AWS CLI installation
  command: "aws --version"
  register: aws_cli_version
  changed_when: false
  become: yes

- name: Show installed AWS CLI version
  debug:
    var: aws_cli_version.stdout



---
# tasks file for common

- name: Install prerequisites for Node.js (Ubuntu)
  become: yes
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Add NodeSource repo for Node.js 18.x (Ubuntu)
  become: yes
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  args:
    executable: /bin/bash
  when: ansible_distribution == "Ubuntu"

- name: Install common packages
  become: yes
  apt:
    name: "{{ item.pk_name }}"
    state: present
    update_cache: yes
  loop: "{{ package_names }}"

- name: Copy Source Code
  become: yes
  synchronize:
    src: "{{ playbook_dir }}/../../"
    dest: "/opt/todo-app"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"
      - "--exclude=todo-frontend"
      - "--exclude=terraform"
