


---
# tasks file for common

- name: Install prerequisites for Node.js (Ubuntu)
  become: yes
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Add NodeSource repo for Node.js 18.x (Ubuntu)
  become: yes
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  args:
    executable: /bin/bash
  when: ansible_distribution == "Ubuntu"

- name: Install common packages
  become: yes
  apt:
    name: "{{ item.pk_name }}"
    state: present
    update_cache: yes
  loop: "{{ package_names }}"

- name: Copy Source Code
  become: yes
  synchronize:
    src: "{{ playbook_dir }}/../../"
    dest: "/opt/todo-app"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"
      - "--exclude=todo-frontend"
      - "--exclude=terraform"
