
# playbook.yml


- name: Provision EC2 instance and push Docker image to ECR
  hosts: localhost
  gather_facts: no
  roles:
    - ecr

- name: Configure EC2 instances
  hosts: launched_ec2_instances
  become: yes
  gather_facts: yes
  roles:
    - common
    - docker

- name: Configure of monitoring EC2 instances
  hosts: monitoring_ec2_instances
  become: yes
  gather_facts: yes
  roles:
    - monitoring