# roles/common/vars/main.yml

#SPDX-License-Identifier: MIT-0
---
# vars file for common
node_package_name:
  Ubuntu:  nodejs
package_names:
  - pk_name: "{{node_package_name[ansible_distribution]}}"
  - pk_name: git
#  - pk_name: docker
