---
- name: Get ECR login token
  shell: "aws ecr get-login-password --region {{ aws_region }}"
  register: ecr_token
  no_log: true

- name: Login into ECR 
  community.docker.docker_login:
    registry_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
    username: AWS
    password: "{{ ecr_token.stdout }}"
    reauthorize: yes

- name: Remove existing Buildx builder named default (if any)
  command: docker buildx rm mybuilder
  ignore_errors: yes

- name: Create and use default Buildx builder with docker-container driver
  command: docker buildx create --name mybuilder  --driver docker-container --use --bootstrap

- name: Build and push backend Docker image
  command: >
    docker buildx build
    --platform linux/amd64,linux/arm64
    -t {{ backend_ecr_uri }}:latest
    --push {{ backend_path }}
  environment:
    DOCKER_BUILDKIT: 1
  register: build_output
  changed_when: true

- name: Show Docker build output
  debug:
    var: build_output.stdout_lines | length > 0
