
---
- name: Get ECR login token
  shell: "aws ecr get-login-password --region {{ aws_region }}"
  register: ecr_token
  no_log: true

- name: Login into ECR 
  community.docker.docker_login:
    registry_url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
    username: AWS
    password: "{{ ecr_token.stdout }}"
    reauthorize: yes

- name: Check if Buildx builder exists
  shell: docker buildx inspect default
  register: buildx_inspect
  failed_when: false
  changed_when: false

- name: Create and use default Buildx builder if not exists
  command: docker buildx create --name default --use
  when: buildx_inspect.rc != 0



- name: Build and push backend Docker image
  command: >
    docker buildx build
    --platform linux/amd64,linux/arm64
    -t {{ backend_ecr_uri }}:latest
    --push {{ playbook_dir }}/../../todo-backend
  environment:
    DOCKER_BUILDKIT: 1
