
name: Deploy TODO App to EC2 using Terraform & Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY_PATH: ~/.ssh/ec2_key.pem
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          pip install ansible boto3 requests
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.docker --force

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform plan 
        run: terraform plan -var-file="environments/dev.tfvars"
        working-directory: terraform        

      - name: Terraform Apply
        run: terraform apply -var-file="environments/dev.tfvars" -auto-approve
        working-directory: terraform

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 400 ~/.ssh/ec2_key.pem

      - name: Check Ansible inventory file
        run: |
          ls -l ansible/
          cat ansible/inventory          


          

      - name: Run Ansible Playbook
        run : |
          ansible-playbook \
          -i ansible/inventory \
          -e "ansible_ssh_private_key_file=~/.ssh/ec2_key.pem" \
          -e "backend_path=${{ github.workspace }}/todo-backend" \
          -e "environment=dev" \
          ansible/playbooks/main.yml 
  
  
      - name: Extract S3 bucket name from inventory
        id: get-bucket
        run: |
         BUCKET_NAME=$(grep "frontend_bucket_name=" ansible/inventory | cut -d"=" -f2)
         echo "bucket_name=$BUCKET_NAME" >> "$GITHUB_OUTPUT"



      - name: Extract cloudfront distribution id from inventory
        id: get-cf-distribution
        run: |
         CF_DISTRIBUTION_NAME=$(grep "cloudfront_distribution_id=" ansible/inventory | cut -d"=" -f2)
         echo "cloudfront_distribution_id=$CF_DISTRIBUTION_NAME" >> "$GITHUB_OUTPUT"

      - name: Deploy Frontend
        run: |
         cd todo-frontend
         ./frontend_deploy.sh "${{ steps.get-bucket.outputs.bucket_name}}" "${{ steps.get-cf-distribution.outputs.cloudfront_distribution_id}}"
        env: 
           AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
