
name: Deploy MERN App to EC2 using Terraform & Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY_PATH: ~/.ssh/ec2_key.pem
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          pip install ansible boto3 requests
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.docker --force

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

#      - name: Terraform Apply
#        run: terraform apply -var-file="environments/dev.tfvars" -auto-approve

#        working-directory: terraform

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Run Ansible Playbook
        run : |
          ansible-playbook \
          -i ansible/inventory \
          -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem" \
          ansible/playbooks/main.yml 


